version: '3.8'
services:
  neo4j:
    image: neo4j:5.3
    container_name: neo4j
    environment:
      NEO4J_AUTH: neo4j/your_password    # Set your desired username and password
      NEO4J_dbms_memory_heap_initial__size: 1G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,gds.*'  # Allow APOC and GDS procedures
    volumes:
      - ./data:/data                    # Persist Neo4j data on the host machine
      - ./logs:/logs                    # Store Neo4j logs on the host machine
      - ./import:/var/lib/neo4j/import  # Directory for importing CSV files
      - ./plugins:/plugins              # Plugin directory for Neo4j extensions
    ports:
      - "7474:7474"  # Neo4j web interface (browser)
      - "7687:7687"  # Bolt protocol for connecting via Neo4j drivers
    restart: unless-stopped
